import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import * as Components from '../components/index';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'La Spaghetteria',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ClerkProvider>
        <html lang='en'>
          <body>
            <Components.Navbar />
            {children}
          </body>
        </html>
      </ClerkProvider>
    </html>
  );
}
